wordpressUsername: admin
wordpressPassword: admin
wordpressEmail: admin@admin.com
wordpressFirstName: Admin
wordpressLastName: Admin
wordpressBlogName: admin.wordpress.com
service:
  type: Loadbalancer